//
//  RecordDetailViewModel.swift
//  REM
//
//  Created by yury antony on 09/06/25.
//

import Foundation
import SwiftData
import os

final class RecordDetailViewModel: ObservableObject {
    // MARK: - Properties
    @Published var trackDate: Bool = false
    @Published var showDeleteConfirmation: Bool = false
    @Published var showExperienceSelector: Bool = false
    @Published var sleepStart: Date = Date()
    
    @Published var date: Date = Date()
    @Published var name: String = ""
    @Published var note: String = ""
    @Published var selectedExperiences: [Experience] = []
    @Published var selectedParalysisDuration: ParalysisDuration = .notSure
    @Published var routineMetrics: RoutineMetrics = RoutineMetrics()
    @Published var visibleSections: Set<RecordDetailSection> = Set(RecordDetailSection.allCases)

    let nameCharacterLimit = 30
    let noteCharacterLimit = 500

    // MARK: - Computed Properties
    var currentLocale: Locale {
        switch LocalizationManager.currentLanguage {
        case .portuguese:
            return Locale(identifier: "pt_BR")
        case .english:
            return Locale(identifier: "en_US")
        }
    }

    var isNameValid: Bool {
        let trimmed = name.trimmingCharacters(in: .whitespacesAndNewlines)
        return !trimmed.isEmpty && trimmed.count <= nameCharacterLimit
    }

    // MARK: - Lifecycle
    func bind(record: Record) {
        date = record.date
        name = RecordNameManager.generateRecordDisplayName(from: record) ?? record.name
        note = record.note ?? ""
        selectedExperiences = record.experiences ?? []
        sleepStart = record.sleepStart ?? Date()
        selectedParalysisDuration = ParalysisDuration(rawValue: record.paralysisDuration ?? ParalysisDuration.notSure.rawValue) ?? .notSure
        trackDate = record.isAutoGeneratedName
        updateVisibleSections(from: record)
    }

    func syncNameIfNeeded() {
        if trackDate {
            name = getRecordName(for: date)
        }
    }

    /// Updates `visibleSections` based on which optional properties of the given record are non-nil.
    /// Call this in the view's `.onAppear` to initialize section visibility.
    func updateVisibleSections(from record: Record) {
        var sections = Set<RecordDetailSection>()
        if record.sleepStart != nil {
            sections.insert(.sleepStart)
        }
        if record.note != nil {
            sections.insert(.note)
        }
        if let exps = record.experiences, !exps.isEmpty {
            sections.insert(.experience)
        }
        if record.paralysisDuration != nil {
            sections.insert(.paralysisDuration)
        }
//        if record.routineMetrics != nil {
//            sections.insert(.routineMetrics)
//        }
//        if record.sleepMetrics != nil {
//            sections.insert(.sleepMetrics)
//        }
        visibleSections = sections
    }

    // MARK: - Validation

    func isModified(for record: Record) -> Bool {
        // Required fields
        if date != record.date || name != record.name {
            return true
        }
        // Optional text field
        if note != (record.note ?? "") {
            return true
        }
        // Experiences list
        if selectedExperiences != (record.experiences ?? []) {
            return true
        }
        // Sleep start
        if visibleSections.contains(.sleepStart) {
            let originalSleep = record.sleepStart ?? sleepStart
            if sleepStart != originalSleep {
                return true
            }
        }
        // Paralysis duration
        if visibleSections.contains(.paralysisDuration) {
            if selectedParalysisDuration.rawValue != (record.paralysisDuration ?? ParalysisDuration.notSure.rawValue) {
                return true
            }
        }
        return false
    }

    func canSave(for record: Record) -> Bool {
        isModified(for: record) && isNameValid
    }

    // MARK: - Actions

    func save(record: Record, context: ModelContext) {
        AppLog.info(.detail, "Saving record id: \(record.id)")
        record.date = date
        record.name = name
        let trimmedNote = note.trimmingCharacters(in: .whitespacesAndNewlines)
        record.note = trimmedNote.isEmpty ? nil : trimmedNote
        record.experiences = selectedExperiences
        record.sleepStart = visibleSections.contains(.sleepStart) ? sleepStart : nil
        record.paralysisDuration = visibleSections.contains(.paralysisDuration) && selectedParalysisDuration != .notSure ? selectedParalysisDuration.rawValue : nil
        record.isAutoGeneratedName = trackDate
        try? context.save()
        AppLog.info(.detail, "Record id: \(record.id) saved")
    }

    func delete(record: Record, context: ModelContext) {
        AppLog.info(.detail, "Deleting record id: \(record.id)")
        context.delete(record)
        try? context.save()
        AppLog.info(.detail, "Record id: \(record.id) deleted")
    }

    // MARK: - Helpers

    func getRecordName(for date: Date) -> String {
        RecordNameManager.generateRecordName(for: date)
    }
    
    func hideSection(_ section: RecordDetailSection) {
        visibleSections.remove(section)
    }
}
