//
//  RecordDetailView.swift
//  REM
//
//  Created by yury antony on 23/05/25.
//

import SwiftUI

struct RecordDetailView: View {
    @Environment(\.modelContext) private var context
    @Environment(\.dismiss) private var dismiss
    
    @ObservedObject var viewModel: FeedViewModel
    let record: Occurrence
    
    @State private var date: Date
    @State private var name: String
    @State private var note: String
    @State private var selectedFeelings: [Experience]
    @State private var trackDate: Bool
    @State private var showDeleteConfirmation = false
    
    enum Field: Hashable {
        case name
        case note
    }
    @FocusState private var focusedField: Field?
    
    private let noteCharacterLimit = 500
    
    init(record: Occurrence, viewModel: FeedViewModel) {
        self.viewModel = viewModel
        self.record = record
        _date = State(initialValue: record.date)
        _name = State(initialValue: viewModel.formattedRecordName(from: record) ?? record.name)
        _note = State(initialValue: record.note)
        _selectedFeelings = State(initialValue: record.experiences ?? [])
        _trackDate = State(initialValue: viewModel.isAutoGeneratedName(in: record))
    }
    
    private var isModified: Bool {
        date != record.date ||
        name != record.name ||
        note != record.note ||
        selectedFeelings != (record.experiences ?? [])
    }
    
    private var dateAndTimeSection: some View {
        Section("Date and time") {
            DatePicker(selection: $date, displayedComponents: [.date, .hourAndMinute]) {
                Label("", systemImage: "clock")
                    .foregroundStyle(.primary)
            }
            .datePickerStyle(.compact)
        }
    }
    
    private var nameSection: some View {
        Section(
            header: HStack {
                Text("Name")
                Spacer()
                Text("Track date")
                Toggle("", isOn: $trackDate)
                    .labelsHidden()
                    .tint(.awake)
            },
            footer: Text("You can define a specific name for this record.")
                .font(.footnote)
        ) {
            TextField("Name", text: $name)
                .focused($focusedField, equals: .name)
                .onChange(of: name) {
                    let autoName = viewModel.getRecordName(for: date)
                    if trackDate && name != autoName {
                        trackDate = false
                    }
                }
        }
    }
    
    private var noteSection: some View {
        Section("Note") {
            ZStack(alignment: .topLeading) {
                if note.isEmpty {
                    Text("Feel free to leave a note about the experience you had, noting whatever details or thoughts you find helpful.")
                        .foregroundColor(.secondary)
                        .padding(8)
                }
                TextEditor(text: $note)
                    .frame(height: 100)
                    .focused($focusedField, equals: .note)
            }
            Text("\(note.count) / \(noteCharacterLimit)")
                .font(.footnote)
                .foregroundColor(note.count > noteCharacterLimit ? .red : .secondary)
        }
    }
    
    private var experienceSection: some View {
        Section("Experience") {
            ExperienceSetterView(selectedExperiences: $selectedFeelings)
        }
    }
    
    private var deleteSection: some View {
        Section {
            HStack {
                Spacer()
                Button("Delete record", role: .destructive) {
                    showDeleteConfirmation = true
                }
                Spacer()
            }
        }
    }
    
    var body: some View {
        Form {
            dateAndTimeSection
            nameSection
            noteSection
            experienceSection
            deleteSection
        }
        .scrollDismissesKeyboard(.immediately)
        .onChange(of: trackDate) {
            if trackDate {
                name = viewModel.getRecordName(for: date)
            }
        }
        .onChange(of: date) {
            if trackDate {
                name = viewModel.getRecordName(for: date)
            }
        }
        .alert("Delete record?", isPresented: $showDeleteConfirmation) {
            Button("Cancel", role: .cancel) { }
            Button("Delete", role: .destructive) {
                viewModel.deleteRecord(record, context: context)
                dismiss()
            }
        } message: {
            Text("This action cannot be undone.")
        }
        .navigationTitle("Edit Record")
        .toolbar {
            ToolbarItem(placement: .navigationBarTrailing) {
                Button("Save") {
                    viewModel.updateRecord(
                        record,
                        newDate: date,
                        newName: name,
                        newNote: note,
                        newExperiences: selectedFeelings,
                        isAutoGeneratedName: trackDate,
                        context: context
                    )
                    dismiss()
                }
                .disabled(!isModified)
            }
        }
    }
}
