//
//  Occurrence.swift
//  sleepprecords
//
//  Created by yury antony on 23/05/25.
//

import Foundation
import SwiftData

@Model
final class Record {
    @Attribute(.unique) var id: UUID
    var date: Date
    var name: String
    var isAutoGeneratedName: Bool = true
    var detailsData: Data?

    init(date: Date = Date(),
         name: String = "",
         isAutoGeneratedName: Bool = true,
         details: RecordDetails = RecordDetails()) {
        self.id = UUID()
        self.date = date
        self.name = name
        self.isAutoGeneratedName = isAutoGeneratedName
        updateDetails(details)
    }

    var details: RecordDetails {
        guard let detailsData else {
            return RecordDetails()
        }

        do {
            return try RecordDetails.decoder.decode(RecordDetails.self, from: detailsData)
        } catch {
            return RecordDetails()
        }
    }

    func updateDetails(_ details: RecordDetails) {
        let prunedDetails = details.pruned
        guard !prunedDetails.isEmpty else {
            detailsData = nil
            return
        }

        detailsData = try? RecordDetails.encoder.encode(prunedDetails)
    }
}
