//
//  Occurrence.swift
//  REM
//
//  Created by yury antony on 23/05/25.
//

import Foundation
import SwiftData

@Model
final class Record {
    @Attribute(.unique) var id: UUID
    var date: Date
    var name: String
    var note: String?
    var experiences: [Experience]?
    var isAutoGeneratedName: Bool = true
    var sleepStart: Date?
    var paralysisDuration: String?
    var sleepMetrics: SleepMetrics?
    var routineMetrics: RoutineMetrics?

    init(
        date: Date = Date(),
        name: String = "",
        note: String? = nil,
        experiences: [Experience]? = nil,
        isAutoGeneratedName: Bool = true,
        sleepStart: Date? = nil,
        paralysisDuration: String? = nil,
        sleepMetrics: SleepMetrics? = nil,
        routineMetrics: RoutineMetrics? = nil
    ) {
        self.id = UUID()
        self.date = date
        self.name = name
        self.note = note
        self.experiences = experiences
        self.isAutoGeneratedName = isAutoGeneratedName
        self.sleepStart = sleepStart
        self.paralysisDuration = paralysisDuration
        self.sleepMetrics = sleepMetrics
        self.routineMetrics = routineMetrics
    }
}
