//
//  RecordDetailView.swift
//  REM
//
//  Created by yury antony on 23/05/25.
//

import SwiftUI
import os

private let paralysisDurations = [
    "Less than 30 seconds",
    "30 s – 1 minute",
    "1 – 2 minutes",
    "More than 2 minutes",
    "Not sure"
]

struct RecordDetailView: View {
    @Environment(\.modelContext) private var context
    @Environment(\.dismiss) private var dismiss
    
    @ObservedObject var viewModel: FeedViewModel
    let record: Record
    
    @State private var date: Date
    @State private var name: String
    @State private var note: String
    @State private var selectedFeelings: [Experience]
    @State private var trackDate: Bool
    @State private var showDeleteConfirmation = false
    @State private var showNoteEditor = false
    @State private var showExperienceSelector = false
    @State private var sleepStart: Date = Date()
    @State private var isSleepStartUnknown: Bool = false
    @State private var selectedParalysisDuration: String = ""
    
    enum Field: Hashable {
        case name
        case note
    }
    @FocusState private var focusedField: Field?
    
    private let noteCharacterLimit = 500
    private let nameCharacterLimit = 50
    
    init(record: Record, viewModel: FeedViewModel) {
        self.viewModel = viewModel
        self.record = record
        _date = State(initialValue: record.date)
        _name = State(initialValue: viewModel.formattedRecordName(from: record) ?? record.name)
        _note = State(initialValue: record.note ?? "")
        _selectedFeelings = State(initialValue: record.experiences ?? [])
        _trackDate = State(initialValue: viewModel.isAutoGeneratedName(in: record))
    }
    
    private var isModified: Bool {
        date != record.date ||
        name != record.name ||
        note != record.note ||
        selectedFeelings != (record.experiences ?? [])
    }
    
    var body: some View {
        ScrollViewReader { proxy in
            Form {
                dateAndTimeSection
                sleepStartSection
                nameSection
                noteSection
                experienceSection
                paralysisDurationSection
                deleteSection
            }
            .scrollDismissesKeyboard(.immediately)
            .onChange(of: trackDate) {
                if trackDate {
                    name = viewModel.getRecordName(for: date)
                }
            }
            .onChange(of: date) {
                if trackDate {
                    name = viewModel.getRecordName(for: date)
                }
            }
            .alert("Delete record?", isPresented: $showDeleteConfirmation) {
                Button("Cancel", role: .cancel) { }
                Button("Delete", role: .destructive) {
                    AppLog.info(.detail, "User confirmed deletion of record id: \(record.id)")
                    viewModel.deleteRecord(record, context: context)
                    dismiss()
                }
            } message: {
                Text("This action cannot be undone.")
            }
            .navigationTitle("Edit Record")
            .onAppear {
                AppLog.info(.detail, "RecordDetailView appeared for record id: \(record.id)")
            }
            .toolbar {
                ToolbarItem(placement: .navigationBarTrailing) {
                    Button("Save") {
                        AppLog.info(.detail, "User tapped Save for record id: \(record.id)")
                        viewModel.updateRecord(
                            record,
                            newDate: date,
                            newName: name,
                            newNote: note,
                            newExperiences: selectedFeelings,
                            isAutoGeneratedName: trackDate,
                            context: context
                        )
                        dismiss()
                    }
                    .disabled(!isModified || name.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty || name.count > nameCharacterLimit)
                }
            }
        }
        .sheet(isPresented: $showNoteEditor) {
            NoteTextEditView(text: $note, maxCharacters: noteCharacterLimit)
        }
    }
    
    private var dateAndTimeSection: some View {
        Section("Date and time") {
            HStack {
                Image(systemName: "calendar")
                Spacer()
                    .foregroundStyle(.primary)
                DatePicker("", selection: $date, displayedComponents: .date)
                    .labelsHidden()
                    .environment(\.locale, viewModel.currentLocale)
            }
            HStack {
                Image(systemName: "clock")
                    .foregroundStyle(.primary)
                Spacer()
                DatePicker("", selection: $date, displayedComponents: .hourAndMinute)
                    .labelsHidden()
                    .environment(\.locale, viewModel.currentLocale)
            }
        }
    }

    private var sleepStartSection: some View {
        Section("Sleep start time") {
            Toggle("Unknown start time", isOn: $isSleepStartUnknown)
                .tint(.awake)
            if !isSleepStartUnknown {
                HStack {
                    Image(systemName: "clock")
                        .foregroundStyle(.primary)
                    DatePicker("", selection: $sleepStart, displayedComponents: .hourAndMinute)
                        .labelsHidden()
                }
            }
        }
    }
    
    private var nameSection: some View {
        Section(
            header: HStack {
                Text("Name")
                Spacer()
                Text("Track date")
                Toggle("", isOn: $trackDate)
                    .labelsHidden()
                    .tint(.awake)
            },
            footer: Text("You can define a specific name for this record.")
                .font(.footnote)
        ) {
            TextField("Name", text: $name)
                .focused($focusedField, equals: .name)
                .onChange(of: name) {
                    let autoName = viewModel.getRecordName(for: date)
                    if trackDate && name != autoName {
                        trackDate = false
                    }
                }
            let remaining = nameCharacterLimit - name.count
            Text("\(remaining)")
                .font(.footnote)
                .foregroundColor(remaining < 0 ? .red : .secondary)
                .padding(.top, 4)
        }
    }
    
    private var noteSection: some View {
        Section(
            header: HStack {
                Text("Note")
                Spacer()
                Button {
                    showNoteEditor = true
                } label: {
                    Image(systemName: "square.and.pencil")
                        .font(.title2)
                        .foregroundStyle(.awake)
                }
            }
        ) {
            
            ZStack(alignment: .topLeading) {
                if note.isEmpty {
                    Text("Feel free to leave a note about the experience you had, noting whatever details or thoughts you find helpful.")
                        .foregroundColor(.secondary)
                        .padding(8)
                }
                Text(note)
                    .padding(8)
                    .frame(maxWidth: .infinity, minHeight: 100, alignment: .topLeading)
            }
            
        }
    }
    
    private var experienceSection: some View {
        Section(
            header: HStack {
                Text("Experience")
                Spacer()
                Button {
                    showExperienceSelector = true
                } label: {
                    Image(systemName: "plus.circle.fill")
                        .font(.title2)
                        .foregroundStyle(.awake)
                }
            }
        ) {
            ExperienceSetterView(selectedExperiences: $selectedFeelings, showingPicker: $showExperienceSelector)
        }
    }
    
    private var paralysisDurationSection: some View {
        Section("Paralysis duration") {
            ForEach(paralysisDurations, id: \.self) { option in
                HStack {
                    Text(option)
                    Spacer()
                    if selectedParalysisDuration == option {
                        Image(systemName: "checkmark")
                            .foregroundColor(.awake)
                    }
                }
                .contentShape(Rectangle())
                .onTapGesture {
                    selectedParalysisDuration = option
                }
            }
        }
    }
    
    private var deleteSection: some View {
        Section {
            HStack {
                Spacer()
                Button("Delete record", role: .destructive) {
                    showDeleteConfirmation = true
                }
                Spacer()
            }
        }
    }
}
