//
//  FeedViewModel.swift
//  REM
//
//  Created by yury antony on 23/05/25.
//

import Foundation
import SwiftData
import os

@MainActor
final class FeedViewModel: ObservableObject {
    @Published var records: [Record] = []
    @Published var sortDescending: Bool = true
    
    var currentLocale: Locale {
        switch LocalizationManager.currentLanguage {
        case .portuguese:
            return Locale(identifier: "pt_BR")
        case .english:
            return Locale(identifier: "en_US")
        }
    }
    
    func fetchRecords(context: ModelContext) {
        AppLog.info(.feedVM, "Starting fetchRecords with sortDescending: \(sortDescending)")
        let descriptor = FetchDescriptor<Record>(
            sortBy: [.init(\.date, order: sortDescending ? .reverse : .forward)]
        )
        records = (try? context.fetch(descriptor)) ?? []
        AppLog.info(.feedVM, "Fetched \(records.count) records")
    }
    
    func addRecord(context: ModelContext, date: Date = Date()) {
        AppLog.info(.feedVM, "Adding new record for date: \(date)")
        let name = getRecordName(for: date)
        let newRecord = Record(date: date, name: name)
        context.insert(newRecord)
        AppLog.debug(.feedVM, "Inserted newRecord: \(newRecord.name)")
        try? context.save()
        fetchRecords(context: context)
        AppLog.info(.feedVM, "addRecord completed and records refreshed")
    }
    
    func getRecordName(for date: Date = Date()) -> String {
        RecordNameManager.generateRecordName(for: date)
    }
    
    func deleteRecord(_ record: Record, context: ModelContext) {
        AppLog.info(.feedVM, "Deleting record with id: \(record.id)")
        context.delete(record)
        AppLog.debug(.feedVM, "Deleted record object: \(record)")
        try? context.save()
        fetchRecords(context: context)
        AppLog.info(.feedVM, "deleteRecord completed and records refreshed")
    }
    
    func updateRecord(
        _ record: Record,
        newDate: Date,
        newName: String,
        newNote: String,
        newExperiences: [Experience]?,
        isAutoGeneratedName: Bool,
        context: ModelContext
    ) {
        AppLog.info(.feedVM, "Updating record with id: \(record.id) to newDate: \(newDate), newName: \(newName)")
        record.date = newDate
        record.name = newName
        record.note = newNote
        record.experiences = newExperiences
        record.isAutoGeneratedName = isAutoGeneratedName
        AppLog.debug(.feedVM, "Record after updates: \(record)")
        try? context.save()
        fetchRecords(context: context)
        AppLog.info(.feedVM, "updateRecord completed and records refreshed")
    }
    
    func isAutoGeneratedName(in record: Record) -> Bool {
        return record.isAutoGeneratedName
    }
    
    func mockRecords(context: ModelContext) {
        AppLog.info(.feedVM, "Starting mockRecords generation")
        for _ in 1...50 {
            let year = Int.random(in: 2024...2025)
            let month = Int.random(in: 1...12)
            let day = Int.random(in: 1...28)
            
            var dateComponents = DateComponents()
            dateComponents.year = year
            dateComponents.month = month
            dateComponents.day = day
            dateComponents.hour = Int.random(in: 0...23)
            dateComponents.minute = Int.random(in: 0...59)
            
            let date = Calendar.current.date(from: dateComponents) ?? Date()
            
            addRecord(context: context, date: date)
            AppLog.debug(.feedVM, "Mock record added for date: \(date)")
        }
        AppLog.info(.feedVM, "mockRecords completed")
    }
    
    func formattedDateTime(for date: Date) -> String {
        let locale = currentLocale
        let formatter = DateFormatter()
        formatter.locale = locale
        formatter.dateStyle = .long
        formatter.timeStyle = .short

        return formatter.string(from: date)
    }
    
    func formattedRecordName(from record: Record) -> String? {
        return RecordNameManager.generateRecordDisplayName(from: record)
    }
}
