//
//  RecordDetailViewModel.swift
//  REM
//
//  Created by yury antony on 09/06/25.
//


import Foundation
import SwiftData
import os

final class RecordDetailViewModel: ObservableObject {
    @Published var date: Date = Date()
    @Published var name: String = ""
    @Published var note: String = ""
    @Published var selectedExperiences: [Experience] = []
    @Published var trackDate: Bool = false
    @Published var showDeleteConfirmation: Bool = false
    @Published var showExperienceSelector: Bool = false
    @Published var sleepStart: Date = Date()
    @Published var selectedParalysisDuration: String = ""

    let nameCharacterLimit = 50
    let noteCharacterLimit = 500

    var currentLocale: Locale {
        switch LocalizationManager.currentLanguage {
        case .portuguese:
            return Locale(identifier: "pt_BR")
        case .english:
            return Locale(identifier: "en_US")
        }
    }

    func getRecordName(for date: Date) -> String {
        RecordNameManager.generateRecordName(for: date)
    }

    func isModified(for record: Record) -> Bool {
        date != record.date ||
        name != record.name ||
        note != record.note ||
        selectedExperiences != (record.experiences ?? [])
    }

    func save(record: Record, context: ModelContext) {
        AppLog.info(.detail, "Saving record id: \(record.id)")
        record.date = date
        record.name = name
        record.note = note
        record.experiences = selectedExperiences
        record.isAutoGeneratedName = trackDate
        try? context.save()
        AppLog.info(.detail, "Record id: \(record.id) saved")
    }

    func delete(record: Record, context: ModelContext) {
        AppLog.info(.detail, "Deleting record id: \(record.id)")
        context.delete(record)
        try? context.save()
        AppLog.info(.detail, "Record id: \(record.id) deleted")
    }

    func bind(record: Record) {
        date = record.date
        name = RecordNameManager.generateRecordDisplayName(from: record) ?? record.name
        note = record.note ?? ""
        selectedExperiences = record.experiences ?? []
        trackDate = record.isAutoGeneratedName
    }

    func syncNameIfNeeded() {
        if trackDate {
            name = getRecordName(for: date)
        }
    }

    func canSave(for record: Record) -> Bool {
        isModified(for: record) && isNameValid
    }

    var isNameValid: Bool {
        let trimmed = name.trimmingCharacters(in: .whitespacesAndNewlines)
        return !trimmed.isEmpty && trimmed.count <= nameCharacterLimit
    }
}
